<template>
  <q-page padding>
    <p>About the System</p>
    <q-separator />
    <p/>
    <h6>Public Investment Program</h6>
    <p>
      The 2017-2022 Public Investment Program (PIP) contains the rolling list of priority programs and projects (PAPs) to be implemented by the national government (NG), government-owned and controlled corporations (GOCCs), government financial institutions (GFIs), and other national government offices and instrumentalities within the medium term (or the plan period from 2017 to 2022), which respond to the outcomes in the Philippine Development Plan (PDP) and its Results Matrices (RM). These PAPs may be financed using national government funds, including internal cash generated by GOCCs, in partnership with the private sector or through Official Development Assistance (ODA).
    </p>
    <p>
      Pursuant to Section 3 of the Executive Order (EO) No. 27 on the implementation of the 2017-2022 Development Plan (PDP) and PIP , and the Special Provision in the General Appropriations Act (GAA) for FY 2018 , NEDA issued on February 7, 2018 a call to agencies for the updating of the 2017-2022 PIP.
    </p>
    <h6>The Investment Programming and Management System (iPMS)</h6>
    <p>
      The
      <strong>iPMS</strong> ...
    </p>
  </q-page>
</template>

<script>
export default {
  name: "PageAbout"
};
</script>

<style></style>
