query users($page:Int!) {
  users(page:$page) {
    data {
      id
      name
      email
      active
      roles {
        id
        name
      }
      created_at
    }
    paginatorInfo {
      currentPage
      lastPage
      total
    }
  }
}