<template>
  <page-container>
    <page-title title="Project Profile">
      <settings-button>
        <q-menu
          transition-show="jump-down"
          transition-hide="jump-up"
          auto-close
        >
          <project-menu
            :project="project"
            :added="added"
            :finalized="finalized"
          ></project-menu>
        </q-menu>
      </settings-button>
    </page-title>

    <template v-if="$apollo.loading">
      <q-inner-loading :showing="$apollo.loading">
        <q-spinner-tail size="50px" color="primary"></q-spinner-tail>
      </q-inner-loading>
    </template>

    <template v-else>
      <project-profile :project="project" />
    </template>

    <q-dialog
      v-model="transferProjectDialog"
      full-height
      :position="$q.screen.xs ? void 0 : 'right'"
      persistent
      :maximized="$q.screen.xs"
      transition-show="jump-left"
      transition-hide="jump-right"
    >
      <transfer-project
        :projectId="$route.params.id"
        @close="transferProjectDialog = false"
      ></transfer-project>
    </q-dialog>
  </page-container>
</template>

<script>
import PageTitle from '@/ui/page/PageTitle.vue';
import PageContainer from '@/ui/page/PageContainer.vue';
import ProjectProfile from '../components/ProjectProfile';
import TransferProject from '../components/dialogs/TransferProject';
import ProjectMenu from '../components/dropdowns/ProjectMenu';
import SettingsButton from '@/ui/buttons/SettingsButton';
import { FETCH_PROJECT_QUERY } from '@/graphql/queries';

export default {
  components: {
    PageContainer,
    PageTitle,
    ProjectProfile,
    TransferProject,
    ProjectMenu,
    SettingsButton
  },
  name: 'ViewProject',
  apollo: {
    project: {
      query: FETCH_PROJECT_QUERY,
      variables() {
        return {
          id: this.$route.params.id
        };
      },
      error(error) {
        console.log(error);
        this.$q
          .dialog({
            title: 'Project not found',
            message: "It's either you don't have access or it has been deleted."
          })
          .onDismiss(() => this.$router.push('/projects'));
      }
    }
  },
  computed: {
    selectedProjects() {
      return this.$store.state.projects.selectedProjects;
    },
    added() {
      return this.selectedProjects.includes(this.project);
    },
    finalized() {
      return this.project ? this.project.latest_status === 'finalized' : false;
    }
  },
  data() {
    return {
      project: {},
      shareProjectDialog: true,
      transferProjectDialog: false
    };
  },
  methods: {
    shareProject() {
      // allow anyone to view the project by appending a pin to the url
      // i should add an autogenerated pin in the projects table
      // send via email, how about token?
    }
  }
};
</script>
