<template>
  <page-container>
    <page-title title="Project Profile">
      <q-btn icon="settings" flat round color="primary">
        <q-menu transition-show="jump-down" transition-hide="jump-up">
          <q-list>
            <q-item clickable :to="`${$route.fullPath}/edit`">
              <q-item-section>
                <q-item-label>Edit Project</q-item-label>
              </q-item-section>
            </q-item>
            <q-item>
              <q-item-section>
                <q-item-label>Print Project</q-item-label>
              </q-item-section>
              <q-item-section side>
                <q-icon name="warning" color="red"></q-icon>
              </q-item-section>
            </q-item>
						<q-item clickable @click="reviewProject = true">
							<q-item-section>
								<q-item-label>Review Project</q-item-label>
							</q-item-section>
						</q-item>
            <q-item clickable @click="shareProjectDialog = true">
              <q-item-section avatar>
                <q-avatar>
                  <q-icon name="share" color="blue"></q-icon>
                </q-avatar>
              </q-item-section>
              <q-item-section>
                <q-item-label>Share Project</q-item-label>
              </q-item-section>
              <q-item-section side>
                <q-icon name="warning" color="red"></q-icon>
              </q-item-section>
            </q-item>
            <q-item clickable @click="transferProjectDialog = true">
              <q-item-section avatar>
                <q-avatar>
                  <q-icon name="share" color="blue"></q-icon>
                </q-avatar>
              </q-item-section>
              <q-item-section>
                <q-item-label>Transfer Project</q-item-label>
              </q-item-section>
            </q-item>
          </q-list>
        </q-menu>
      </q-btn>
    </page-title>

    <template v-if="$apollo.loading">
      <q-inner-loading :showing="$apollo.loading">
        <q-spinner-tail size="50px" color="primary"></q-spinner-tail>
      </q-inner-loading>
    </template>

    <template v-else>
      <project-profile :id="$route.params.id" />
    </template>

    <q-dialog 
      v-model="transferProjectDialog"
      full-height
      :position="$q.screen.xs ? void 0 : 'right'"
      persistent
      :maximized="$q.screen.xs"
      transition-show="jump-left"
      transition-hide="jump-right">
      <transfer-project :projectId="$route.params.id" @close="transferProjectDialog = false"></transfer-project>
    </q-dialog>

  </page-container>
</template>

<script>
import { FETCH_PROJECT_QUERY } from '../../../graphql/queries';
import PageTitle from '@/ui/page/PageTitle.vue';
import PageContainer from '@/ui/page/PageContainer.vue';
import { date } from 'quasar'
import ProjectProfile from '../components/ProjectProfile'
import TransferProject from '../components/dialogs/TransferProject'

export default {
  components: { PageContainer, PageTitle, ProjectProfile, TransferProject },
  name: 'ViewProject',
  data() {
    return {
      shareProjectDialog: true,
      transferProjectDialog: false
    }
  },
  methods: {
    shareProject() {
      // allow anyone to view the project by appending a pin to the url
      // i should add an autogenerated pin in the projects table
      // send via email, how about token?
    }
  }
};
</script>
